In [1]:
import numpy as np

In [7]:
vector = np.arange(1,11,1)
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
matriz = np.random.rand(3,3)
matriz

array([[0.9587504 , 0.24850231, 0.72016473],
       [0.09920784, 0.86166323, 0.50188554],
       [0.72552554, 0.09696726, 0.87337974]])

In [16]:
matriz_identidad = np.eye(4)
matriz_identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
matriz_vector = np.reshape(vector,(2,5))
matriz_vector

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
matriz_vector[matriz_vector>5]

array([ 6,  7,  8,  9, 10])

In [19]:
arreglo_1 = np.array([1,2,3,4,5])
arreglo_2 = np.array([6,7,8,9,10])
arreglo_3 = arreglo_1 + arreglo_2
arreglo_3

array([ 7,  9, 11, 13, 15])

In [20]:
raiz_arreglo = np.sqrt(arreglo_3)
raiz_arreglo

array([2.64575131, 3.        , 3.31662479, 3.60555128, 3.87298335])